Myblog/Myblog/urls.py
from django.contrib import admin
from django.urls import path
from django .conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'',include('blog.url')),
    url(r'',include('comments.urls')),
]

Myblog/comments/urls.py
from django.conf.urls import url
from . import views
app_name='comments'
urlpatterns=[
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

Myblog/blog/models.py
# coding=utf-8
from django.db import models
from django.contrib.auth.models import  User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100)

    class Meta:
        verbose_name_plural='分类'

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)
    class Meta:
        verbose_name_plural='标签'

    def __str__(self):
        return self.name

class Post(models.Model):

    #文章标题
    title=models.CharField(max_length=70,verbose_name='标题')
    #正文
    body=models.TextField(verbose_name='正文')
    #创建时间
    create_time=models.DateTimeField(verbose_name='创建时间')
    #最后一次修改时间
    modified_time=models.DateTimeField(verbose_name='最近修改时间')
    #文章摘要
    excerpt=models.CharField(max_length=200,blank=True,verbose_name='摘要')
    category=models.ForeignKey(Category,on_delete=True,verbose_name='分类')
    tag=models.ManyToManyField(Tag,blank=True)
    author=models.ForeignKey(User,on_delete=True,verbose_name='作者')
    views=models.PositiveIntegerField(default=0,verbose_name='阅读量')
    def increase_views(self):
        self.views+=1
        self.save(update_fields=['views'])

    class Meta:
        verbose_name_plural='文章'
        ordering=['-create_time']
    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    def save(self,*args,**kwargs):
        #如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md=markdown.Markdown(extensions=[
                'markdown,extensions.extra',
                'markdown.extensions.codehilite',
            ])
            #先将 Markdown 文本渲染成 HTML 文本
            #strip_tags 去掉 HTML 文本的全部 HTML 标签
            #从文本摘取前 54 个字符赋给 excerpt
            self.excerpt=strip_tags(md.convert(self.body))[:54]

        #调用父类的save方法将数据保存到数据库中
        super(Post,self).save(*args,**kwargs)

Myblog/comments/models.py
#coding=utf-8
from django.db import models

# Create your models here.
class Comment(models.Model):
    name=models.CharField(max_length=100,verbose_name='名称')
    email=models.EmailField(max_length=255,verbose_name='邮箱')
    url=models.URLField(blank=True)
    text=models.TextField(verbose_name='评论')
    created_time=models.DateTimeField(auto_now_add=True,verbose_name='评论时间')

    post=models.ForeignKey('blog.Post',on_delete=True,verbose_name='评论文章')

    def __str__(self):
        return self.text[:20]

    class Meta:
        verbose_name_plural='评论表'

Myblog/blog/views.py
#coding:utf-8
import markdown
from django.shortcuts import render,HttpResponse,get_object_or_404
from . models import Post ,Category,Tag
from comments.forms import CommentForm
from django.views.generic import ListView,DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension

# Create your views here.
# def index(request):
#     '''
#     主页
#     '''
#     post_list=Post.objects.all().order_by('-create_time')
#     return render(request,'blog/index.html',{'post_list':post_list})
class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'
    #指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章
    paginate_by = 1

    def get_context_data(self,**kwargs):
        #首先获得父类生成的传递给模板的字典
        context =super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page=context.get('page_obj')
        is_paginated = context.get('is_paginated')

        #调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)
        return context

    def pagination_data(self,paginator, page, is_paginated):
        if not is_paginated:
            return {}

        left=[]
        right=[]
        left_has_more=False
        right_has_more=False

        #如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        first=False
        last=False

        #获得用户当前请求的页码号
        page_number=page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        #获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number==1:
            right=page_range[page_number:page_number+2]

            #如果最右边的页码号比最后一页的页码号减去 1 还要小，说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，
            if right[-1]<total_pages-1:
                right_has_more=True
            if right[-1] < total_pages:
                last = True

        elif page_number ==total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            if left[0] > 2:
                left_has_more = True

        else:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            #是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data




# def detail(request,pk):
#     #如果文章不存在，则返回404错误
#     post=get_object_or_404(Post,pk=pk)
#     #阅读量+1
#     post.increase_views()
#     post.body=markdown.markdown(post.body,
#                                 extensions=[
#                                     'markdown.extensions.extra',
#                                     'markdown.extensions.codehilite', #语法高亮拓展
#                                     'markdown.extensions.toc',        #自动生成目录
#                                 ])
#     form=CommentForm()
#     #获取这篇文章下的全部评论
#     comment_list=post.comment_set.all()
#
#     #将文章、表单、以及文章下的评论列表作为模板变量传给detail
#     context={'post':post,
#              'form':form,
#              'comment_list':comment_list
#     }
#     return render(request,'blog/detail.html',context=context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self,request,*args,**kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post
        response=super(PostDetailView,self).get(request,*args,**kwargs)

        #将文章量加一，注意self.object的值就是被访问的文章post
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        #覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染
        post=super(PostDetailView,self).get_object(queryset=None)
        md=markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite', #语法高亮拓展
            TocExtension(slugify=slugify),
        ])
        post.body=md.convert(post.body)
        post.toc=md.toc
        return post

    def get_context_data(self, **kwargs):
        #还要把评论表单、post 下的评论列表传递给模板。
        context=super(PostDetailView,self).get_context_data(**kwargs)
        form=CommentForm()
        # 获取这篇文章下的全部评论
        comment_list=self.object.comment_set.all()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context


# def archives(request,year,month):
#     post_list=Post.objects.filter(create_time__year=year,
#                                   create_time__month=month
#                                   ).order_by('-create_time')
#     return render(request,'blog/index.html',{'post_list':post_list})

class ArchivesView(IndexView):
    def get_queryset(self):
        year=self.kwargs.get('year')
        month=self.kwargs.get('month')
        return super(ArchivesView,self).get_queryset().filter(create_time__year=year,
                                                              create_time__month=month
                                                              )


# def category(request,pk):
#     cate=get_object_or_404(Category,pk=pk)
#     post_list=Post.objects.filter(category=cate).order_by('-create_time')
#     return render(request,'blog/index.html',{'post_list':post_list})

class CategoryView(IndexView):

    #覆写父类的get_queryset方法，因其默认获取全部列表数据
    def get_queryset(self):
        cate=get_object_or_404(Category,pk=self.kwargs.get('pk'))
        return super(CategoryView,self).get_queryset().filter(category=cate)


class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag=get_object_or_404(Tag,pk=self.kwargs.get('pk'))
        return super(TagView,self).get_queryset().filter(tag=tag)

Myblog/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }}阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>
        <div class="comment-list-panel">
            <h3>评论列表，共 <span>4</span> 条评论</h3>
            {% for comment in comment_list %}
            <ul class="comment-list list-unstyled">
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date" >{{ comment.created_time }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                暂无评论
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}
{%  block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

Myblog/templates/blog/index.html
{% extends 'base.html' %}
{% block main %}
    {% for post in post_list %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' post.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.create_time }}">{{ post.create_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{% url 'blog:detail' post.pk %}">{{ post.comment_set.count }}评论</a></span>
                <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}


    <!-- 简单分页效果
    <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
    </div>
    -->
    {% if is_paginated %}
        <div class="pagination-simple">
            <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
        {% endif %}
        <!-- 显示当前页面信息 -->
        <span class="current">第{{ page_obj.number }}页 / 共{{ paginator.num_pages }}页</span>
        <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->
        {%  if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
        {% endif %}
        </div>
    {% endif %}
    {% if is_paginated %}
    <div class="pagination">
    {% if first %}
        <a href="?page=1">1</a>
    {% endif %}
    {% if left %}
        {% if left_has_more %}
            <span>...</span>
        {% endif %}
        {% for i in left %}
            <a href="?page={{ i }}">{{ i }}</a>
        {% endfor %}
  {% endif %}
  <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
  {% if right %}
    {% for i in right %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
        <span>...</span>
    {% endif %}
  {% endif %}
  {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  {% endif %}
    </div>
    {% endif %}
{% endblock main %}